applications:
  - name: example-app
    namespace: default
    project: default
    source:
      repoURL: https://github.com/juliacheperis13/goit-devops-hw.git
      path: charts/django-app 
      targetRevision: lesson-db-module
      helm:
        valueFiles:
          - values.yaml
    destination:
      server: https://kubernetes.default.svc
      namespace: default
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

repositories:
  - name: example-app
    url: https://github.com/juliacheperis13/goit-devops-hw.git
    username: ${github_user}
    password: ${github_pat}

repoConfig:
  insecure: "true"
  enableLfs: "true"
