adminUser: admin
adminPassword: admin123

service:
  type: NodePort
  port: 80
  nodePort: 32000

persistence:
  enabled: true
  size: 2Gi
  storageClassName: gp2

resources:
  requests:
    memory: 256Mi
    cpu: 100m
  limits:
    memory: 512Mi
    cpu: 200m

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server.monitoring.svc.cluster.local
        access: proxy
        isDefault: true

dashboards:
  default:
    node-exporter:
      gnetId: 1860
      revision: 27
      datasource: Prometheus

    k8s-cluster:
      gnetId: 315
      revision: 2
      datasource: Prometheus

    prometheus-stats:
      gnetId: 3662
      revision: 1
      datasource: Prometheus

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: default
        orgId: 1
        folder: ""
        type: file
        disableDeletion: false
        updateIntervalSeconds: 30
        options:
          path: /var/lib/grafana/dashboards/default
