image:
  repository: 498777148926.dkr.ecr.us-east-1.amazonaws.com/lesson-5-ecr
  tag: v1.0.11
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 8000

ingress:
  enabled: false

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70
